name: dynamic_choice_chip
description: This flutter plugin can be used to render the dynamic choice chip, where developer can pass the list.
version: 0.0.1
homepage: https://github:com/satyambarsainya/dynamic_choice_chip

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  assorted_layout_widgets: ^5.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.dynamic_choice_chip
        pluginClass: DynamicChoiceChipPlugin
      ios:
        pluginClass: DynamicChoiceChipPlugin